[build]
  base = "deploy-6a25c0b5b971448233fc1a51"
  command = "npm install"
  publish = "."
  functions = "functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "STRIPE_WEBHOOK_SECRET,STRIPE_SECRET_KEY"
